/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
  "/api/version": {
    /** Version */
    get: operations["version_api_version_get"];
  };
  "/api/workspace": {
    /** Read Workspace */
    get: operations["read_workspace_api_workspace_get"];
  };
  "/api/workspace/reset": {
    /** Reset Workspace */
    post: operations["reset_workspace_api_workspace_reset_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** CanaryStatus */
    CanaryStatus: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Credits Usd */
      credits_usd: number | null;
      /** Ok */
      ok: boolean;
    };
    /** HealthOut */
    HealthOut: {
      canary?: components["schemas"]["CanaryStatus"] | null;
      /**
       * Db
       * @enum {string}
       */
      db: "ok" | "unavailable";
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded";
    };
    /** VersionOut */
    VersionOut: {
      /** Models */
      models: {
        [key: string]: string;
      };
      /** Version */
      version: string;
    };
    /** WorkspaceOut */
    WorkspaceOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthOut"];
        };
      };
      /** @description Service Unavailable */
      503: {
        content: {
          "application/json": components["schemas"]["HealthOut"];
        };
      };
    };
  };
  /** Version */
  version_api_version_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VersionOut"];
        };
      };
    };
  };
  /** Read Workspace */
  read_workspace_api_workspace_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceOut"];
        };
      };
    };
  };
  /** Reset Workspace */
  reset_workspace_api_workspace_reset_post: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
}
