import hashlib
import shutil
import time
import zipfile
from pathlib import Path

import docx
import pytest

from app.text import contains
from datakit import render, validate
from datakit.extract import lines_of, text_of
from datakit.render import parse_md, render_docx, render_pack, render_pdf, render_xlsx
from datakit.schemas import Facts, load_yaml
from datakit.validate import CONTROL_ACRONYMS, CONTROL_STEMS, CONTROL_WORDS, DATA, STAGES

SAMPLE = (
    "# Access Control Policy\n\n"
    "User access to internal systems is reviewed quarterly.\n\n"
    "- MFA is required.\n\n"
    "| System | Owner |\n|---|---|\n| Okta | Dana Ortiz |\n"
)
SPEC = {
    "sheet": "Access reviews",
    "title": "Kestrelyn access review log",
    "as_of": "2026-09-15",
    "headers": ["System", "Status"],
    "rows": [["Okta", "Overdue"]],
}


def test_parse_md_blocks() -> None:
    assert parse_md(SAMPLE) == [
        ("h", 1, "Access Control Policy"),
        ("p", "User access to internal systems is reviewed quarterly."),
        ("li", "MFA is required."),
        ("table", ("System", "Owner"), (("Okta", "Dana Ortiz"),)),
    ]


def test_docx_and_pdf_keep_every_sentence(tmp_path: Path) -> None:
    for render_one, name in ((render_docx, "a.docx"), (render_pdf, "a.pdf")):
        path = tmp_path / name
        render_one(parse_md(SAMPLE), path)
        text = text_of(path)
        assert contains(text, "User access to internal systems is reviewed quarterly.")
        assert contains(text, "System: Okta; Owner: Dana Ortiz")


def test_xlsx_records(tmp_path: Path) -> None:
    path = tmp_path / "a.xlsx"
    render_xlsx(SPEC, path)
    assert "System: Okta; Status: Overdue" in text_of(path)
    assert "As of: 2026-09-15" in text_of(path)


def test_render_is_deterministic(tmp_path: Path) -> None:
    a = render_pack("dev", tmp_path / "a")
    b = render_pack("dev", tmp_path / "b")

    def digest(paths: list[Path]) -> list[str]:
        return [hashlib.sha256(p.read_bytes()).hexdigest() for p in paths]

    assert digest(a) == digest(b)


def _sample_files(folder: Path) -> list[Path]:
    render_docx(parse_md(SAMPLE), folder / "a.docx")
    render_pdf(parse_md(SAMPLE), folder / "a.pdf")
    render_xlsx(SPEC, folder / "a.xlsx")
    return [folder / "a.docx", folder / "a.pdf", folder / "a.xlsx"]


def test_bytes_do_not_depend_on_the_clock(tmp_path: Path) -> None:
    first = _sample_files(tmp_path / "first")
    time.sleep(1.1)  # the formats stamp whole seconds
    second = _sample_files(tmp_path / "second")
    assert [p.read_bytes() for p in first] == [p.read_bytes() for p in second]


def test_office_zips_are_stored_and_pdfs_are_not_compressed(tmp_path: Path) -> None:
    docx_path, pdf_path, xlsx_path = _sample_files(tmp_path)
    for path in (docx_path, xlsx_path):  # normalize_zip: no zlib, one creating OS, no tool name
        with zipfile.ZipFile(path) as z:
            assert {i.compress_type for i in z.infolist()} == {zipfile.ZIP_STORED}, path.name
            assert {i.create_system for i in z.infolist()} == {3}, path.name
            assert {i.date_time for i in z.infolist()} == {(2026, 1, 1, 0, 0, 0)}, path.name
            assert b"<Application>" not in z.read("docProps/app.xml"), path.name
    assert b"FlateDecode" not in pdf_path.read_bytes()  # compressed streams would depend on the zlib build
    assert docx.Document(str(docx_path)).core_properties.comments == ""  # no "generated by python-docx"


def test_the_docs_stage_passes_on_the_dev_pack() -> None:
    assert STAGES["docs"]("dev") == []


@pytest.fixture
def pack(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A rendered copy of the dev pack that the docs stage and the renderer both read instead of data/."""
    root = tmp_path / "data" / "dev"
    root.mkdir(parents=True)
    shutil.copy(DATA / "dev" / "facts.yaml", root / "facts.yaml")
    shutil.copytree(DATA / "dev" / "src", root / "src")
    monkeypatch.setattr(render, "ROOT", tmp_path)
    monkeypatch.setattr(validate, "DATA", tmp_path / "data")
    render_pack("dev")
    return root


def test_the_docs_stage_flags_a_sentence_split_across_lines(pack: Path) -> None:
    assert STAGES["docs"]("dev") == []
    source = pack / "src" / "dcp.md"
    source.write_text(source.read_text().replace("deleted within 30 days", "deleted\n\nwithin 30 days"))
    render_pack("dev")
    assert STAGES["docs"]("dev") == [
        "statement dcp-deletion not found verbatim in data-classification-policy.md"
    ]


def test_the_docs_stage_flags_a_stale_file_a_missing_file_and_non_ascii_source(pack: Path) -> None:
    (pack / "docs" / "security-faq.md").write_text("changed\n")
    (pack / "docs" / "bcp-dr-plan.docx").unlink()
    (pack / "src" / "wiki.md").write_text("café\n", encoding="utf-8")
    found = STAGES["docs"]("dev")
    assert "missing rendered file bcp-dr-plan.docx" in found
    assert "wiki.md is not ASCII" in found
    assert "security-faq.md is stale: run python -m datakit.render dev" in found
    assert not [p for p in found if "bcp-dr-plan.docx is stale" in p]  # reported once, as missing


def _units(path: Path) -> list[str]:
    lines = lines_of(path)
    if path.suffix == ".pdf":  # one long line per PDF: split into sentences
        return [
            s.strip() + ("" if s.strip().endswith(".") else ".") for s in lines[0].split(". ") if s.strip()
        ]
    return lines


def test_no_unregistered_control_keywords() -> None:
    facts = load_yaml(DATA / "dev" / "facts.yaml", Facts)
    allowed_file = DATA / "dev" / "src" / "ALLOWED_LINES.txt"
    allowed = {ln.split(" # ")[0].strip() for ln in allowed_file.read_text().splitlines() if ln.strip()}
    loose = []
    for d in facts.documents:
        registered = [s.text for s in facts.statements if s.doc == d.id]
        for unit in _units(DATA / "dev" / "docs" / d.filename):
            if (
                CONTROL_WORDS.search(unit)
                and unit not in allowed
                and not any(r in unit or unit in r for r in registered)
            ):
                loose.append(f"{d.filename}: {unit[:120]}")
    assert loose == []


# Leak sentences that a reviewer used to probe the keyword net; each one must be flagged. Three of them use
# acronyms that only match as whole words; the last three use an un- prefix, a plural acronym and a hyphenated
# phrase.
PROBES = (
    "Office key-fob access is logged.",
    "A diagram of how customer data moves is maintained.",
    "HSTS and CSP response headers are set.",
    "Developers are trained on injection flaws.",
    "Customers sign in using OIDC.",
    "Kestrelyn holds cyber liability coverage of USD 10,000,000.",
    "Reports go to the security@ mailbox.",
    "Employees sign in through SSO.",
    "Reports are shared under an NDA.",
    "The contract includes an SLA.",
    "Laptop disks are unencrypted.",
    "Reports are shared under NDAs.",
    "We run a bug-bounty program.",
)
# Words that merely contain an acronym: "sso", "nda" and "sla" are inside them.
LOOKALIKES = ("lesson", "association", "agenda", "islands")


def test_the_keyword_net_flags_every_probe_sentence() -> None:
    assert [p for p in PROBES if not CONTROL_WORDS.search(p)] == []
    assert CONTROL_WORDS.search("Access is reviewed.")  # a stem matches at a word start, with any ending
    words = [*CONTROL_STEMS, *CONTROL_ACRONYMS]
    variants = [v for w in words for v in (w, w.replace(" ", "-"), w.replace("-", " "))]
    unmatched = [v for v in variants if not CONTROL_WORDS.search(v)]
    assert unmatched == []  # every stem and acronym finds itself, with a space or a hyphen between its words


def test_the_keyword_net_does_not_match_inside_words() -> None:
    sentence = "The association shared the lesson and the agenda on the islands."
    assert [t for t in (*LOOKALIKES, sentence) if CONTROL_WORDS.search(t)] == []
    assert not CONTROL_WORDS.search("A preview of the roadmap.")  # "review" is a stem, not a substring
