"""initial schema

Revision ID: 030c8f33dc18
Revises:
Create Date: 2026-10-04 00:18:32.219538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '030c8f33dc18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canary_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canary_runs_at'), 'canary_runs', ['at'], unique=False)
    op.create_table('ip_limits',
    sa.Column('ip_hash', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ip_hash', 'window_start', 'kind')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspaces_created_at', 'workspaces', ['created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=8), server_default='final', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('evidence_allowed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata_source', sa.String(length=8), server_default='rule', nullable=False),
    sa.Column('line_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('policy', 'report', 'record', 'contract', 'plan', 'questionnaire', 'statement', 'other')", name='ck_documents_kind'),
    sa.CheckConstraint("metadata_source IN ('rule', 'model', 'user')", name='ck_documents_metadata_source'),
    sa.CheckConstraint("source IN ('sample', 'upload', 'drive', 'statement')", name='ck_documents_source'),
    sa.CheckConstraint("status IN ('final', 'draft')", name='ck_documents_status'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('hour_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'hour_start', 'kind')
    )
    op.create_table('questionnaires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('original_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('sheet', sa.String(length=255), nullable=True),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('sample', 'upload', 'drive')", name='ck_questionnaires_source'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_workspace_id'), 'questionnaires', ['workspace_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('flags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(heading, '') || ' ' || text)", persisted=True), nullable=False),
    sa.CheckConstraint("flags <@ ARRAY['negation', 'placeholder', 'injection']::text[]", name='ck_chunks_flags'),
    sa.CheckConstraint('line_start >= 1 AND line_end >= line_start', name='ck_chunks_lines'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_workspace_id'), 'chunks', ['workspace_id'], unique=False)
    op.create_table('document_lines',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('n >= 1', name='ck_document_lines_n'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'n')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('row_ref', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('csf_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'position', name='uq_items_position')
    )
    op.create_index(op.f('ix_items_questionnaire_id'), 'items', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_items_workspace_id'), 'items', ['workspace_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('models', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'done', 'failed')", name='ck_runs_status'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_questionnaire_id'), 'runs', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_runs_workspace_id'), 'runs', ['workspace_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=8), nullable=True),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('dropped', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('conflict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_note', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0', nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(citations) = 'array' AND jsonb_typeof(dropped) = 'array'", name='ck_answers_json_arrays'),
    sa.CheckConstraint("label <> 'user_confirmed' OR statement_id IS NOT NULL", name='ck_answers_statement'),
    sa.CheckConstraint("label IN ('verified', 'partial', 'conflict', 'unknown', 'user_confirmed', 'na')", name='ck_answers_label'),
    sa.CheckConstraint("label NOT IN ('verified', 'partial') OR jsonb_array_length(citations) > 0", name='ck_answers_cited'),
    sa.CheckConstraint("value IS NULL OR value IN ('Yes', 'No', 'Partial')", name='ck_answers_value'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_answers_confidence'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'item_id', name='uq_answers_run_item')
    )
    op.create_index(op.f('ix_answers_item_id'), 'answers', ['item_id'], unique=False)
    op.create_index(op.f('ix_answers_run_id'), 'answers', ['run_id'], unique=False)
    op.create_index(op.f('ix_answers_workspace_id'), 'answers', ['workspace_id'], unique=False)
    op.create_table('run_items',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=8), server_default='pending', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('pending', 'claimed', 'done')", name='ck_run_items_state'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'item_id')
    )
    op.create_index('ix_run_items_state', 'run_items', ['run_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_items_state', table_name='run_items')
    op.drop_table('run_items')
    op.drop_index(op.f('ix_answers_workspace_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_run_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_item_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_runs_workspace_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_questionnaire_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_items_workspace_id'), table_name='items')
    op.drop_index(op.f('ix_items_questionnaire_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('document_lines')
    op.drop_index(op.f('ix_chunks_workspace_id'), table_name='chunks')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_questionnaires_workspace_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_workspaces_created_at', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('ip_limits')
    op.drop_index(op.f('ix_canary_runs_at'), table_name='canary_runs')
    op.drop_table('canary_runs')
    # ### end Alembic commands ###
