"""Render document sources (data/<pack>/src) into the files a visitor uploads (data/<pack>/docs).

Sources are a small Markdown subset (#/##/### headings, paragraphs, "- " bullets, pipe tables) for docx, pdf
and md outputs, and YAML for spreadsheets. Output is byte-identical on every run and on every machine: fixed
timestamps, Office zips through normalize_zip (stored members, no tool name), PDFs without compressed streams.
python -m datakit.render dev"""

import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import docx
import openpyxl
import yaml
from fpdf import FPDF
from openpyxl.styles import Font

from app.text import record_line
from datakit.questionnaires import normalize_zip
from datakit.schemas import Facts, load_yaml

ROOT = Path(__file__).resolve().parent.parent
FIXED = datetime(2026, 1, 1, tzinfo=UTC)
AUTHOR = "Kestrelyn"
Block = tuple[Any, ...]


def _cells(line: str) -> tuple[str, ...]:
    return tuple(c.strip() for c in line.strip().strip("|").split("|"))


def parse_md(text: str) -> list[Block]:
    blocks: list[Block] = []
    para: list[str] = []
    table: list[tuple[str, ...]] = []

    def flush() -> None:
        if para:
            blocks.append(("p", " ".join(para)))
            para.clear()
        if table:
            blocks.append(("table", table[0], tuple(table[1:])))
            table.clear()

    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip():
            flush()
        elif line.lstrip().startswith("|"):
            if para:
                flush()
            if not set(line.replace("|", "").strip()) <= {"-", ":", " "}:
                table.append(_cells(line))
        elif line.startswith("#"):
            flush()
            level = len(line) - len(line.lstrip("#"))
            blocks.append(("h", level, line.lstrip("#").strip()))
        elif line.lstrip().startswith("- "):
            flush()
            blocks.append(("li", line.lstrip()[2:].strip()))
        else:
            para.append(line.strip())
    flush()
    return blocks


def render_docx(blocks: list[Block], path: Path) -> None:
    d = docx.Document()
    props = d.core_properties
    props.created = props.modified = props.last_printed = FIXED.replace(tzinfo=None)
    props.author = props.last_modified_by = AUTHOR
    props.comments = ""  # the default template says "generated by python-docx"
    for b in blocks:
        if b[0] == "h":
            d.add_heading(b[2], level=min(b[1], 3))
        elif b[0] == "p":
            d.add_paragraph(b[1])
        elif b[0] == "li":
            d.add_paragraph(b[1], style="List Bullet")
        else:
            headers, rows = b[1], b[2]
            t = d.add_table(rows=1 + len(rows), cols=len(headers))
            t.style = "Table Grid"
            for r, values in enumerate((headers, *rows)):
                for c, value in enumerate(values):
                    t.rows[r].cells[c].text = value
    path.parent.mkdir(parents=True, exist_ok=True)
    d.save(str(path))
    normalize_zip(path)


def render_pdf(blocks: list[Block], path: Path) -> None:
    pdf = FPDF()
    pdf.set_creation_date(FIXED)
    pdf.set_compression(False)  # deflated streams would depend on the zlib build
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    for b in blocks:
        if b[0] == "h":
            pdf.set_font("Helvetica", style="B", size={1: 15, 2: 13}.get(b[1], 11))
            pdf.multi_cell(0, 7, b[2], new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)
        elif b[0] in ("p", "li"):
            pdf.set_font("Helvetica", size=10.5)
            pdf.multi_cell(0, 5, b[1] if b[0] == "p" else f"- {b[1]}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
        else:
            pdf.set_font("Helvetica", size=10)
            for row in b[2]:
                pdf.multi_cell(0, 5, record_line(b[1], row), new_x="LMARGIN", new_y="NEXT")
                pdf.ln(1)
    path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(path))


def render_xlsx(spec: dict[str, Any], path: Path) -> None:
    wb = openpyxl.Workbook()
    wb.properties.created = wb.properties.modified = FIXED.replace(tzinfo=None)
    wb.properties.creator = AUTHOR
    ws = wb.active
    ws.title = spec["sheet"]
    ws["A1"] = spec["title"]
    ws["A1"].font = Font(bold=True, size=13)
    ws["A2"] = f"As of: {spec['as_of']}"
    for col, text in enumerate(spec["headers"], start=1):
        ws.cell(4, col, text).font = Font(bold=True)
    for r, values in enumerate(spec["rows"], start=5):
        for c, value in enumerate(values, start=1):
            ws.cell(r, c, value)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(path))
    normalize_zip(path)


def render_pack(pack: str, out: Path | None = None) -> list[Path]:
    base = ROOT / "data" / pack
    out = out or base / "docs"
    facts = load_yaml(base / "facts.yaml", Facts)
    written = []
    for doc in facts.documents:
        target = out / doc.filename
        if doc.format == "xlsx":
            render_xlsx(yaml.safe_load((base / "src" / f"{doc.id}.yaml").read_text(encoding="utf-8")), target)
        else:
            source = base / "src" / f"{doc.id}.md"
            if doc.format == "md":
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)
            elif doc.format == "docx":
                render_docx(parse_md(source.read_text(encoding="utf-8")), target)
            else:
                render_pdf(parse_md(source.read_text(encoding="utf-8")), target)
        written.append(target)
    return written


if __name__ == "__main__":
    for p in render_pack(sys.argv[1] if len(sys.argv) > 1 else "dev"):
        print(p.relative_to(ROOT))
